apiVersion: v1
kind: Pod
metadata:
  labels:
    run: file-mod-challenge
  name: file-mod-challenge
spec:
  containers:
  - image: jenksgibbons/file_mod_challenge:1.0
    name: file-mod-challenge
    securityContext:
      capabilities:
        add: ["LINUX_IMMUTABLE"]